#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

function usage() {
  console.log('Usage: node scripts/import-models.js <source-folder>');
  console.log('Example: node scripts/import-models.js "C:/datasets/fruit-glb"');
}

const src = process.argv[2];
if (!src) {
  usage();
  process.exit(1);
}

const absSrc = path.resolve(process.cwd(), src);
if (!fs.existsSync(absSrc) || !fs.statSync(absSrc).isDirectory()) {
  console.error('Source folder not found or not a directory:', absSrc);
  process.exit(2);
}

const publicModelsDir = path.resolve(process.cwd(), 'public', 'models');
if (!fs.existsSync(publicModelsDir)) fs.mkdirSync(publicModelsDir, { recursive: true });

const files = fs.readdirSync(absSrc).filter(f => /\.(glb|gltf)$/i.test(f));
if (files.length === 0) {
  console.log('No .glb/.gltf files found in', absSrc);
  process.exit(0);
}

const copied = [];
files.forEach((f) => {
  const srcPath = path.join(absSrc, f);
  const destName = f.replace(/\s+/g, '_');
  const destPath = path.join(publicModelsDir, destName);
  fs.copyFileSync(srcPath, destPath);
  copied.push(destName);
});

// Build fruits list: detect base names and sliced variants
const byBase = {};
copied.forEach((name) => {
  // normalize name: remove extension
  const base = name.replace(/\.[^.]+$/, '');
  if (/_sliced$/i.test(base)) {
    const root = base.replace(/_sliced$/i, '');
    byBase[root] = byBase[root] || {};
    byBase[root].sliced = name;
  } else {
    byBase[base] = byBase[base] || {};
    byBase[base].whole = name;
  }
});

const fruits = Object.keys(byBase).map((key) => {
  const entry = byBase[key];
  return {
    id: key.toLowerCase(),
    name: key.replace(/[-_]/g, ' ').replace(/\b\w/g, c => c.toUpperCase()),
    modelPath: entry.whole ? `${importMetaBase()}models/${entry.whole}` : null,
    slicedModelPath: entry.sliced ? `${importMetaBase()}models/${entry.sliced}` : null
  };
});

function importMetaBase() {
  // during runtime in browser we'll use import.meta.env.BASE_URL; here write simple root path
  return '/';
}

const outPath = path.resolve(process.cwd(), 'src', 'data', 'fruits.js');
const contents = `// Auto-generated by scripts/import-models.js
const fruits = ${JSON.stringify(fruits, null, 2)};

export default fruits;
`;
fs.writeFileSync(outPath, contents, 'utf8');

console.log('Copied', copied.length, 'files to public/models');
console.log('Generated', outPath);
console.log('Entries:', fruits.length);
